"""Evidence-based warehouse descriptions; query findings are appended after execution."""
import json,re
from pathlib import Path
root=Path(__file__).resolve().parents[2]
A={
'dimensions': 'The business process is retail order-item sales. Following Kimball’s four steps, the design selects the process, declares one original order item as the grain, identifies dimensions and defines measures (Kimball Group, n.d.-a). A consistent grain prevents accidental mixing of order totals and item-level measures (Kimball Group, n.d.-b).\n\nFactSales preserves a unique OrderItemID, while SalesKey is its surrogate primary key. OrderID and ItemSequence are degenerate identifiers. Six required foreign keys connect Customer, Product, Seller, purchase Date and two roles of Geography. Customer contains exact source age, gender and integrated education. Product flattens category and subcategory into one dimension, avoiding a snowflake. Seller retains registration information, including the original textual end date. Date uses a YYYYMMDD key with year, quarter, month and day. Geography distinguishes customer destinations from seller origins through GeographyRole and a unique role-location pair. These dimensions support demographic, regional, product and annual supplier comparisons (Kimball & Ross, 2013).\n\nThe transaction snapshot contains 137,901 facts, 21,000 customers, 2,199 products, 100 sellers, 493 dates and 1,599 geography rows. Geography includes 1,500 customer locations and 99 distinct seller locations. One seller-location ID has conflicting TAS and WA mappings; its state is explicitly UNK and contradictory details are null, while both original CSV records remain preserved.\n\nAdditive quantity and LineAmount support the required queries. UnitSalesPrice is a unit-rate measure, so it must not be summed as revenue. Source floats remain available alongside four-decimal amounts, recomputed extended amount and the difference from the supplied line total. Missing freight remains null. All order statuses are retained, but delivered orders form the completed-sales proxy. No source costs establish profit, and no history supports Type 2 changes. This is a snapshot warehouse, not an inferred historical record.',
'implementation': 'The SSIS master package resets only the allowlisted student warehouse, then runs eleven Data Flow Tasks in success order. Four Flat File Source flows preserve the complete age, education, state and seller-location CSV records. OLE DB Source queries project original operational fields; native Lookup transformations integrate references and assign dimension keys. Derived Column transformations normalise education codes, create date attributes and calculate measures, while Data Conversion enforces destination types (Microsoft, n.d.).\n\nProduct joins its subcategory and category through Lookups. Geography resolves customer states and masks the contradictory seller location before a native Sort removes the duplicate transformed location. The date flow derives calendar fields and sorts to one row per date. FactSales looks up order attributes and six dimension roles, retaining unmatched-row failure dispositions. Native Row Count components record each destination count.\n\nDirect conversion from floating-point amounts originally truncated some fourth-decimal values. The corrected Derived Column expressions round scaled amounts to integral ten-thousandths, then use exact numeric division. Raw floats remain unchanged for audit. Fast-load destinations enable CHECK_CONSTRAINTS, and the reset validates and restores constraint trust. No SQL joins or INSERT SELECT statements load warehouse data.\n\nCounts, source-field comparisons, monetary checks and relationship tests accompany execution. The warehouse must also pass an actual backup restore and full-row comparison before its backup is accepted.'
}
B={
'dimensions': 'The model begins with OzMart’s sales process and fixes the fact grain at one operational order item. Dimensions and measures follow that declaration, applying the four-step dimensional design method (Kimball Group, n.d.-a). Keeping this grain explicit prevents order-level and item-level quantities from being combined incorrectly (Kimball Group, n.d.-b).\n\nFactSales has a surrogate SalesKey and a unique source OrderItemID. OrderID and ItemSequence identify the underlying transaction without separate dimensions. Required keys link each item to Customer, Product, Seller, purchase Date and two Geography roles. Customer supports exact-age segmentation and retains both raw and normalised education codes. Product combines product, subcategory and category attributes for a direct star-schema join. Seller describes the registered provider. Date exposes calendar periods through a YYYYMMDD key. Geography supplies destination and supplier-origin attributes from the same role-aware table, allowing the NSW supplier question to use origin independently of the state receiving purchases. Flattened dimensions simplify the required queries (Kimball & Ross, 2013).\n\nThe loaded snapshot comprises 137,901 items and 688,367 units. Dimension counts are 21,000 customers, 2,199 products, 100 sellers, 493 dates and 1,599 geographic role-location pairs. The 100 raw seller-location records describe only 99 unique IDs. One ID has contradictory state and address information; a single transformed UNK record preserves the uncertainty instead of selecting a preferred state. Raw conflicting rows remain auditable.\n\nItemQuantity and supplied LineAmount are additive. UnitSalesPrice is not an additive revenue measure. Separate raw floats, rounded amounts, price-times-quantity totals and discrepancies permit reconciliation. Freight remains null because the source supplies no values. Queries use delivered orders as a completed-sales proxy while retaining other statuses in the fact table. Revenue does not establish profit without costs. Dimensions describe the supplied snapshot; historical changes are not invented.',
'implementation': 'An independent SSIS master package sequences four CSV reference flows, seller, customer, product, two geography roles, date and fact loading. Its reset targets only the named student warehouse. Original-source SQL performs field projection; data integration occurs in SSIS transformations. Native Row Count components expose eleven destination counts.\n\nCustomer education uses Sorted inputs and Merge Join, followed by Lookup-based age integration. Derived Column retains the original education code and forms its normalised key. Product Lookups flatten category hierarchy. Customer Geography combines operational locations with state references; Seller Geography preserves the source conflict as UNK before Sort removes the transformed duplicate. The Date task derives calendar attributes and eliminates repeated dates.\n\nFactSales integrates order attributes and dimension keys through native Lookups, failing unresolved matches rather than silently dropping rows. Data Conversion maps explicit target types (Microsoft, n.d.). Amounts are rounded to integral ten-thousandths before exact numeric division, correcting truncation observed in an earlier native run. Source floats remain unchanged. Missing freight is explicitly null. All destinations check constraints during fast loading; reset-time validation restores trust.\n\nThe final controls reconcile counts, original fields, monetary calculations, foreign-key roles and source transaction relationships. Actual backup restoration and full-row comparison provide a separate delivery check. The process uses no SQL INSERT SELECT integration.'
}
if __name__=='__main__':
 for s,sections in [('A',A),('B',B)]:
  counts={k:len(re.findall(r'\S+',v)) for k,v in sections.items()}
  assert counts['dimensions']<=400 and counts['implementation']<=300,counts
  path=root/'submission'/f'Student_{s}'/'report/warehouse_sections_draft.json'
  path.write_text(json.dumps({'sections':sections,'word_counts':counts},indent=2)+'\n')
  print(s,counts)
