"""Evidence-bound report sections; learner conclusions are frozen before holdout."""
COMMON = {
'process': 'The untouched CSV supplied 14,999 records. I excluded 5,000 missing targets and one malformed target, leaving 9,998 labelled customers. Customer ID became an identifier, and default became the label. A stratified split reserved a fixed test set. Five-fold stratified cross-validation used the training partition only. Missing-value imputation and removal of unused nominal values were fitted inside each training fold. Logistic regression also used dummy encoding and standardisation. The fitted preprocessing models were applied unchanged to validation and test records. No resampling or test-driven tuning occurred (Kohavi, 1995).',
'recommendations': 'Banks should treat these models as exploratory evidence. All four fixed test evaluations missed every default, so the present operating rules cannot support automatic lending decisions. Accuracy near 89% largely reflects the prevalence of non-default customers. Precision and recall deserve priority when defaults are uncommon (Saito & Rehmsmeier, 2015).\n\nCollect payment histories, debt-service ratios, loan duration, interest rates and the dates at which each predictor became available. Audit missingness and confirm that features precede default. A subsequent study should predefine loss-sensitive thresholds and precision-recall criteria on new training data, then validate once on an untouched later cohort. The current test set must not become a tuning resource.\n\nInvestigate age, income, borrowing purpose and financial buffers as associations requiring confirmation. Coefficients do not establish that changing these characteristics changes default risk. Evaluate calibration and expected loss, including the costs of missed defaults and incorrectly rejecting reliable applicants. Human reviewers should assess affordability using verified evidence while any predictive system remains outside operational eligibility decisions.',
'ethics': 'A model that misses every default can create false confidence and expose customers to unaffordable credit. The present classifiers should therefore remain research tools. A future system would need documented performance criteria, independent validation and clear accountability before it influenced lending.\n\nAge and education can encode demographic differences, while income and financial circumstances can reflect historical disadvantage. Removing a sensitive attribute alone does not remove proxy discrimination (Mehrabi et al., 2019). Compare error rates, calibration and outcomes across legally and ethically appropriate groups, with sufficient sample sizes and uncertainty estimates. The supplied data do not establish that any model satisfies a fairness criterion.\n\nUse only necessary customer information, restrict access, document retention and record consent or other appropriate authority for processing. Explanations should distinguish predictive associations from causal reasons and should allow customers to challenge inaccurate records. A small model coefficient does not justify a categorical claim about a person.\n\nKeep a human review and appeal process, log model versions and decisions, and monitor changes in customer populations. Review disagreements between predicted risk and verified affordability. Transparent disclosure of the failed default recall is essential: a high overall accuracy should not be presented as proof of safe or equitable lending.'
}
A = {
'process': 'Of 14,999 original records, 5,000 lacked targets and one had a malformed target; 9,998 were eligible. Customer ID was assigned the identifier role and default the label. A stratified split with seed 2202 reserved 1,999 customers for testing. Five-fold stratified cross-validation used only the 7,999 training records. Imputation and nominal-vocabulary removal were fitted within training folds; logistic regression additionally used dummy encoding and standardisation. The fitted preprocessing models transformed validation records unchanged. Fourteen financial and demographic predictors were retained. No resampling or holdout-driven tuning occurred (Kohavi, 1995).',
'predictors': 'The native logistic model assigned negative weights to standardised age (-0.214), academic associate education (-0.235) and masters education (-0.181). These conditional associations depend on coding and correlated inputs; they do not demonstrate causal protection. The selected decision tree contained only a non-default leaf, so it identified no decisive split predictor (Quinlan, 1986). This contrast limits business interpretation: the logistic model ranks some customers differently, while the tree provides no segmentation. RapidMiner implements this operator through myKLR, so the exported weights should not be described as estimates from a separately fitted conventional regression (RapidMiner, n.d.).',
'comparison': 'Training-only cross-validation gave logistic regression AUC 0.647 and pooled default F1 1.40%; the decision tree achieved AUC 0.500 and no default detections. I therefore selected logistic regression for investigation before examining the test set. On 1,999 held-out customers, logistic regression achieved 89.34% accuracy and AUC 0.625, versus 89.39% and 0.500 for the tree. Both had zero default recall. Logistic regression produced one false positive; the tree predicted non-default throughout. Native F1 was undefined because no defaults were correctly identified; count-derived F1 was zero. Logistic regression offers some ranking information, but neither model is suitable for bank lending. Majority-class accuracy obscures failed minority detection, so precision-recall evidence is essential (Saito & Rehmsmeier, 2015). The holdout was not used to alter model settings or selection (Kohavi, 1995).'
}
B = {
'process': 'The original 14,999-row CSV yielded 9,998 valid labelled customers after excluding 5,000 missing targets and one malformed target. Customer ID served as the identifier. Stratified sampling with seed 2203 allocated 6,999 records to training and 2,999 to the holdout. Twelve predictors excluded education and weekly work hours. Five stratified folds estimated training performance. Each fold fitted its own imputation and nominal-vocabulary preprocessing; logistic regression also fitted dummy encoding and standardisation. Validation and test records received only the training-fitted transformations. Neither oversampling nor test-based parameter changes were used (Kohavi, 1995).',
'recommendations': 'The bank should withhold these classifiers from operational lending. Both classified every test customer as non-default, including all 318 customers who had defaulted. Their 89.40% accuracy therefore adds no default-detection value at the tested rule. Logistic regression provides modest ranking evidence, but that does not establish an acceptable screening threshold (Saito & Rehmsmeier, 2015).\n\nA further study should examine repayment timing, instalment burden, verified disposable income, loan terms and changes in financial buffers. Check whether each feature was available before the outcome. Investigate the observed age, capital-gain, income and borrowing-purpose associations through uncertainty estimates and subgroup analysis; avoid assuming that they identify causes.\n\nThe forest produced only non-default leaves. Investigate whether more informative, timely predictors improve discrimination in a new study with a predefined training protocol. Specify expected-loss and calibration criteria before selecting thresholds, and reserve a genuinely new cohort for evaluation. The existing holdout cannot support another independent model-selection claim.\n\nQualified staff should assess verified affordability, document reasons and review disputed records while predictive work remains experimental.',
'ethics': 'The main ethical limitation is the failure to identify any default in the test set. Presenting overall accuracy as a dependable risk assessment would conceal this failure. Customers and the bank could bear the consequences of unsuitable credit, so the current model should not determine eligibility.\n\nThis process omitted education, race, gender and geographic origin from its predictors. Those omissions do not demonstrate fairness: income, age and financial variables may still encode unequal opportunities or act as proxies (Mehrabi et al., 2019). Before any future deployment, assess subgroup recall, false-positive rates and calibration with adequate observations and uncertainty estimates. Examine competing fairness definitions in the context of the lending objective, rather than claiming that one metric proves equitable treatment.\n\nLimit data collection to relevant, verified information, restrict access and establish a justified retention period. Explain the role and limitations of the model to applicants. Provide a route to correct inaccurate inputs and appeal decisions, with a responsible human reviewer who can reconsider evidence.\n\nMaintain records of training data, preprocessing, model versions and subsequent decisions. Monitor changes in outcomes and population composition, and suspend use when predefined performance requirements fail. The observed coefficients describe conditional associations; they do not justify treating an individual as inherently risky or safe.',
'predictors': 'The native logistic model assigned negative weights to standardised age (-0.142), capital gain (-0.096), income above $250,000 (-0.174) and small-business loan purpose (-0.235). These associations depend on coding and the remaining predictors; they are neither causal effects nor reliable grounds for accepting applicants. Every tree in the 50-tree forest was a non-default leaf, so the forest supplied no split-based variable importance (Breiman, 2001). The logistic operator uses myKLR, and its exported weights should be interpreted within that implementation rather than attributed to a separately estimated conventional regression (RapidMiner, n.d.).',
'comparison': 'Cross-validation gave logistic regression AUC 0.601 and random forest AUC 0.500. Neither detected defaults, leaving the primary native F1 criterion unresolved. Logistic regression was retained only for its secondary ranking evidence before the holdout. Among 2,999 test customers, both models achieved 89.40% accuracy and zero default recall; every prediction was non-default. Logistic regression AUC was 0.595, while forest AUC remained 0.500. Native precision and F1 were undefined, and count-derived F1 was zero. The 50-tree ensemble provided no advantage at this operating rule (Breiman, 2001). Banks should deploy neither model. Class imbalance makes overall accuracy inadequate, and default-focused performance must guide a new, independently validated study (Saito & Rehmsmeier, 2015). No holdout-driven retuning or reselection occurred (Kohavi, 1995).'
}
if __name__=='__main__':
 import json,re
 from pathlib import Path
 root=Path(__file__).resolve().parents[2]
 for s,extra in [('A',A),('B',B)]:
  result=COMMON|extra
  limits={'process':100,'predictors':100,'comparison':150,'recommendations':200,'ethics':250}
  counts={k:len(re.findall(r"\S+",v)) for k,v in result.items()}
  assert all(counts[k]<=limits[k] for k in counts),(s,counts)
  (root/'submission'/f'Student_{s}'/'report/model_sections_draft.json').write_text(json.dumps({'sections':result,'word_counts':counts},indent=2)+'\n')
  print(s,counts)
