"""Build independent report narratives from verified warehouse outputs."""
from pathlib import Path
import csv,json,re
ROOT=Path(__file__).resolve().parents[2]
for student in 'AB':
 p=ROOT/'submission'/f'Student_{student}'
 rows={q:list(csv.DictReader((p/'evidence/sql'/f'{q}-0.csv').open(encoding='utf-8-sig'))) for q in ['Q4_1','Q4_2','Q4_3']}
 assert len(rows['Q4_1'])==8 and len(rows['Q4_2'])==40
 if student=='A':
  summary='OzMart’s warehouse integrates 137,901 order items through eleven native SSIS data flows. Five dimensions support customer, product, supplier, calendar and regional analysis. Original measures and statuses remain auditable; delivered orders define the completed-sales proxy. Source costs and universally missing freight prevent a reliable profit calculation.\n\nCustomer revenue leaders differ substantially across states: the leading exact ages range from 19 in ACT to 85 in Tasmania. Toys & Games leads delivered unit sales in all eight states, including 24,667 units in NSW. NSW-origin supplier Erin Marquez leads both 2022 and 2023 with 833 and 598 units. Dense ranking preserves ties, so the 2021 top-five-rank supplier result contains seven suppliers. These observations describe the supplied period and do not establish causal customer preferences or future demand.\n\nLoan modelling uses 9,998 labelled records, an independent 80/20 split and training-only five-fold cross-validation. Logistic regression and a decision tree both miss every held-out default. Logistic regression has test AUC 0.625, compared with 0.500 for the tree, but accuracy around 89% conceals zero default recall. Neither model supports automatic lending. Future work needs verified temporal predictors, predeclared loss-sensitive evaluation and new independent validation, alongside privacy, fairness and human review controls.'
  q1='Revenue is SUM(LineAmount) for delivered items, grouped by customer destination state and exact source age. DENSE_RANK retains all age groups sharing the highest revenue (Microsoft, 2026). The result contains one winner per state: ACT 19, NSW 57, NT 71, QLD 40, SA 81, TAS 85, VIC 35 and WA 31. NSW age 57 contributes 44,167.3311 in the source currency. These are aggregate revenue profiles, not per-customer spending estimates; cohort size and purchase frequency may explain differences. No currency conversion or causal targeting effect is assumed.'
  q2='Product type means the product category, and best-selling means delivered units rather than revenue or distinct order lines. Ranking is partitioned by customer destination state; DENSE_RANK retains tied category positions. The actual output has five categories in each of eight states, with no included ties. Toys & Games ranks first everywhere: NSW contributes 24,667 units, VIC 17,914 and QLD 17,836. Revenue is shown as supporting context. The result supports category-level stock review, but does not reveal margins, inventory availability or future demand.'
  q3='NSW suppliers means suppliers whose own location is in NSW, consistent with the supplier-origin interpretation. Delivered quantity is grouped by purchase year and seller. The contradictory location marked UNK is excluded from an NSW-specific result. Michelle Wells leads 2021 with 23 units; Erin Marquez leads 2022 and 2023 with 833 and 598. DENSE_RANK includes five distinct quantity ranks, giving seven suppliers in 2021 and five in each later year. A separate customer-destination NSW sensitivity returns different suppliers and 21 rows overall, demonstrating that the geographical interpretation matters. The calendar groups represent the supplied observation period; they should not be assumed to be equally complete years.'
 else:
  summary='The retail analysis uses a separate warehouse containing 137,901 original order items and five dimensions. Eleven native SSIS data flows load reference data, dimensions and facts. The customer integration uses sorted Merge Join inputs, while warehouse measures retain both raw source values and explicitly rounded amounts. Delivered orders form the sales analysis population. Profit cannot be calculated reliably without costs and freight.\n\nThe strongest exact-age revenue profile varies by destination state, from age 19 in ACT to age 85 in Tasmania. Toys & Games is the unit-sales leader in every state; NSW records 24,667 delivered units. Among NSW-origin suppliers, Michelle Wells leads 2021 with 23 units and Erin Marquez leads 2022 and 2023 with 833 and 598. Deterministic row numbering returns exactly five suppliers per year and resolves quantity ties by seller identity.\n\nThe loan experiment reserves 2,999 of 9,998 eligible customers through a stratified 70/30 split. Training-only cross-validation compares logistic regression with a 50-tree random forest. Both fixed test classifiers miss every default. Logistic regression’s test AUC is 0.595 versus the forest’s 0.500; approximately 89% accuracy reflects class imbalance. The evidence supports further research, not operational eligibility decisions. New temporal data, loss-sensitive thresholds defined before validation, subgroup checks and accountable human review are necessary before deployment could be considered.'
  q1='The query aggregates delivered LineAmount by destination state and exact customer age. ROW_NUMBER partitions by state, orders revenue descending and uses age ascending as the deterministic tie-breaker (Microsoft, n.d.). Each state therefore returns one profile. The observed winners match the other independently loaded warehouse: ages 19, 57, 71, 40, 81, 85, 35 and 31 for ACT, NSW, NT, QLD, SA, TAS, VIC and WA respectively. NSW age 57 has revenue 44,167.3311 in the supplied currency. Aggregate totals cannot distinguish population size from individual spending, so they do not establish that an age group is intrinsically more valuable.'
  q2='The category dimension defines product types. SUM(ItemQuantity) measures best-selling categories among delivered items, grouped by customer destination state. ROW_NUMBER uses category ID as a stable secondary ordering and returns exactly five categories where available. There are 40 result rows. Toys & Games leads all eight states; its units range from 255 in ACT to 24,667 in NSW. VIC and QLD record 17,914 and 17,836 units. These regional volumes can guide a stock-planning investigation, although costs, stockouts and the length of observation would be needed for an investment decision.'
  q3='The main analysis identifies sellers located in NSW and totals their delivered item quantities within purchase year. ROW_NUMBER sorts quantity descending and SellerID ascending. It returns 15 rows: five suppliers for each of 2021, 2022 and 2023. Michelle Wells sells 23 units as the 2021 leader. Erin Marquez leads the following two years at 833 and 598 units. In 2021, Amy Trevino and Jason Long both sell 21 units; seller identity decides their third and fourth positions. A separate destination-based NSW query also returns 15 rows but selects different suppliers. Origin and destination answer different questions; neither should be silently substituted. Differences between calendar years may reflect observation coverage as well as sales activity.'
 out={'sections':{'executive_summary':summary,'query_4_1':q1,'query_4_2':q2,'query_4_3':q3},'word_counts':{'executive_summary':len(summary.split())},'source_rows':{q:len(v) for q,v in rows.items()}}
 assert out['word_counts']['executive_summary']<=250
 (p/'report/query_sections_draft.json').write_text(json.dumps(out,indent=2)+'\n')
 print(student,out['word_counts'])
